<?php involve('security');?>
<?= topbar('Prestige Gold Vault') ?>

    <!-- hero start -->
    <section class="hero bg_img" data-background="vv/assets/images/bg/hero.jpg">
      <div class="container">
        <div class="row">
          <div class="col-xl-5 col-lg-8">
            <div class="hero__content">
              <h2 class="hero__title"><span class="text-white font-weight-normal">Invest for Future in Stable Platform</span> <b class="base--color">and Make Fast Money</b></h2>
              <p class="text-white f-size-18 mt-3">If you are a relatively modest investor of physical bullion bars and coins, then a popular and cost effective method of storing it is at home. If you do opt for this method of storing your bullion at home then be creative. Hide it somewhere unusual, somewhere where if you did encounter anintruder they would not stumble across it by accident.</p>
              <a href="vaultauthenticator" class="cmn-btn text-uppercase font-weight-600 mt-4">Open Vault</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- hero end -->

    <!-- cureency section start -->
    <div class="cureency-section">
      <div class="container">
      </div>
    </div>
    <!-- cureency section end  -->

    <!-- about section start -->
    <section class="about-section pt-120 pb-120 bg_img" data-background="vv/assets/images/bg/bg-2.jpg">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 offset-lg-6">
            <div class="about-content">
              <h2 class="section-title mb-3"><span class="font-weight-normal">About</span> <b class="base--color">Us</b></h2>
              <p>We have worked hard to put together a storage solution that provides our customers with access to high security professionally managed vaults, insurance, direct ownership of their holdings and independent audits.</p>
              <p class="mt-4">  We strongly believe our vaulting service offers a much better solution than a safety deposit box. Bank safety deposit boxes are becoming increasingly expensive, difficult to find and do not include insurance.</p>
              <a href="#0" class="cmn-btn mt-4">MORE INFO</a>
            </div><!-- about-content end -->
          </div>
        </div>
      </div>
    </section>
    <!-- about section end -->

    <!-- package section start -->
    <!-- package section end  -->

    <!-- choose us section start -->
    <section class="pt-120 pb-120 overlay--radial bg_img" data-background="vv/assets/images/bg/bg-3.jpg">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6 text-center">
            <div class="section-header">
              <h2 class="section-title"><span class="font-weight-normal">Why Choose</span> <b class="base--color">Storing Gold Bullion</b></h2>
              <p> The physical possession and control of your bullion is one of the main benefits of investing in physical gold bullion over electronic or paper gold, however, you must consider where to store your investment. There really is no one correct answer - the truth is you can do with it as you please and can store it where you like; it really is down to personal preference.</p>
            </div>
          </div>
        </div><!-- row end -->
        <div class="row justify-content-center mb-none-30">
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="lar la-copy"></i>
                </div>
                <h4 class="choose-card__title base--color">Legal Company</h4>
              </div>
              <p>Our company conducts absolutely legal activities in the legal field. We are certified to operate investment business, we are legal and safe.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-lock"></i>
                </div>
                <h4 class="choose-card__title base--color">High reliability</h4>
              </div>
              <p>We are trusted by a huge number of people. We are working hard constantly to improve the level of our security system and minimize possible risks.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-user-lock"></i>
                </div>
                <h4 class="choose-card__title base--color">Special Offers</h4>
              </div>
              <p>Our Special Offers category contains our latest discounted bullion products available at low premiums above the global spot precious metal prices. These gold and silver bars and coins are discounted from our usual bullion prices, and are not of a reduced precious metal content or quality. </p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-shipping-fast"></i>
                </div>
                <h4 class="choose-card__title base--color">Investment Gold Bars</h4>
              </div>
              <p>All our investment gold bars, often known as gold ingots, bricks or biscuits, are competitively priced with the larger bars representing the very best value for money. For individuals looking for a flexible investment our 1 ounce gold bars could be ideal.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-users"></i>
                </div>
                <h4 class="choose-card__title base--color">Buy Gold Bars</h4>
              </div>
              <p> We stock a complete range of bullion bars available at low premiums, and including free, fully insured delivery. All our bars are pure 24ct gold with a fineness of 999.9 and are delivered either brand new in excellent condition or pre-owned in good or better condition.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-headset"></i>
                </div>
                <h4 class="choose-card__title base--color">24/7 Support</h4>
              </div>
              <p>We provide a 24/7 nationwide service with a wide range of our own fully trained, locksmith, access control and safe engineers providing installation, delivery, service and maintenace across the Globe</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-server"></i>
                </div>
                <h4 class="choose-card__title base--color">Dedicated Server</h4>
              </div>
              <p>We are using a dedicated server for the website which allows us exclusive use of the resources of the entire server.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="fab fa-expeditedssl"></i>
                </div>
                <h4 class="choose-card__title base--color">Secured</h4>
              </div>
              <p>Available in a vast array of shapes and sizes – making sure that our clients can achieve the highest secure storage solution within their premises, regardless of the spacial requirements or limitations there may be.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-shield-alt"></i>
                </div>
                <h4 class="choose-card__title base--color">Certification</h4>
              </div>
              <p>Our Vaults and Strong Rooms are constructed to meet certification in accordance with the European standard EN-1143-1, offering enhanced burglary protection for your valued assets.</p>
            </div><!-- choose-card end -->
          </div>
        </div>
      </div>
    </section>
    <!-- choose us section end  -->

    <!-- how work section end  -->

    
    <!-- faq section end -->


    
    <!-- testimonial section end -->

    <!-- team section start -->
    <!-- team section end -->


    <!-- data section end -->


    <!-- top investor section start -->
 
    <!-- top investor section end -->


    <!-- cta section start -->
    <!-- cta section end -->

    <!-- payment brand section start -->
    <!-- payment brand section end -->

    
    <!-- blog section start -->
    <!-- blog section end -->

    <!-- subscribe section start -->
    <!-- subscribe section end -->


    <!-- footer section start -->
    <?= footerbar();?>

  </body>


</html> 