<?php involve('security');?>
<?= topbar('Services-Royal  Vault') ?>

    

    
    <!-- inner hero start -->
    <section class="inner-hero bg_img" data-background="vv/assets/images/bg/bg-5.jpg">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h2 class="page-title">Our Services</h2>
            <ul class="page-breadcrumb">
              <li><a href="index-2.html">Home</a></li>
              <li>Services</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <!-- inner hero end -->


    <!-- how work section start -->
    <!-- how work section end  -->


    <!-- about section start -->
    
    
    <section class="pt-120 pb-120 overlay--radial bg_img" data-background="assets/images/bg/bg-3.jpg">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6 text-center">
            <div class="section-header">
              <h2 class="section-title"><span class="font-weight-normal">Why Choose</span> <b class="base--color">Prestige Gold Vault</b></h2>
              <p>Our goal is to provide our investors with a reliable source of high income, while minimizing any possible risks and offering a high-quality service.</p>
            </div>
          </div>
        </div><!-- row end -->
        <div class="row justify-content-center mb-none-30">
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="lar la-copy"></i>
                </div>
                <h4 class="choose-card__title base--color">Legal Company</h4>
              </div>
              <p>Our company conducts absolutely legal activities in the legal field. We are certified to operate investment business, we are legal and safe.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-lock"></i>
                </div>
                <h4 class="choose-card__title base--color">High reliability</h4>
              </div>
              <p>We are trusted by a huge number of people. We are working hard constantly to improve the level of our security system and minimize possible risks.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-user-lock"></i>
                </div>
                <h4 class="choose-card__title base--color">Anonymity</h4>
              </div>
              <p>We have worked hard to put together a storage solution that provides our customers with access to high security professionally managed vaults, insurance, direct ownership of their holdings and independent audits.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-shipping-fast"></i>
                </div>
                <h4 class="choose-card__title base--color">Available for Storage</h4>
              </div>
              <p>We're offering investors the opportunity to securely store any of the products on our website. This covers our full range of gold, silver and platinum bars and coins and even extends to our proof coins and box sets</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-users"></i>
                </div>
                <h4 class="choose-card__title base--color">Referral Program</h4>
              </div>
              <p>There is no minimum or maximum holding so you can store any amount of bullion you choose. You can add to your holdings by placing new orders at any time and will only be charged one fee based on the total value of your holdings..</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-headset"></i>
                </div>
                <h4 class="choose-card__title base--color">24/7 Support</h4>
              </div>
              <p>We provide 24/7 customer support through e-mail and telegram. Our support representatives are periodically available to elucidate any difficulty..</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-server"></i>
                </div>
                <h4 class="choose-card__title base--color">Dedicated Server</h4>
              </div>
              <p>We are using a dedicated server for the website which allows us exclusive use of the resources of the entire server.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="fab fa-expeditedssl"></i>
                </div>
                <h4 class="choose-card__title base--color">SSL Secured</h4>
              </div>
              <p>Comodo Essential-SSL Security encryption confirms that the presented content is genuine and legitimate.</p>
            </div><!-- choose-card end -->
          </div>
          <div class="col-xl-4 col-md-6 mb-30">
            <div class="choose-card border-radius--5">
              <div class="choose-card__header mb-3">
                <div class="choose-card__icon">
                  <i class="las la-shield-alt"></i>
                </div>
                <h4 class="choose-card__title base--color">DDOS Protection</h4>
              </div>
              <p>We are using one of the most experienced, professional, and trusted DDoS Protection and mitigation provider.</p>
            </div><!-- choose-card end -->
          </div>
        </div>
      </div>
    </section>
    
    
    
    <!-- about section end -->

    <!-- team section start -->
    <!-- team section end -->

    <!-- faq section start -->
    <!-- faq section end -->

    <!-- cta section start -->
    <!-- cta section end -->

    
    <?= footerbar();?>
  </body>


</html> 